apiVersion: batch/v1
kind: Job
metadata:
  name: check-couchdb-up
spec:
  template:
    spec:
      containers:
      - name: check-couchdb-up
        image: public.ecr.aws/medic/couchdb-migration:1.0.2
        command: ["/bin/sh", "-c"]
        args: ["check-couchdb-up $NUMBER_OF_NODES"]
        env:
        - name: NUMBER_OF_NODES
          value: "<replace_with_number_of_nodes>"
        - name: COUCH_URL
          valueFrom:
            secretKeyRef:
              name: cht-secrets
              key: COUCH_URL
        envFrom:
        - configMapRef:
            name: env-config
        - secretRef:
            name: env-secrets
      restartPolicy: Never
